from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AIResponse(BaseModel):
    """Structured response schema returned by the AI Engine."""
    success: bool = Field(..., description="Status of pipeline execution success")
    response: str = Field(..., description="The natural language conversational response text")
    action: str = Field(..., description="The classified main intent or action name")
    plan: Optional[List[str]] = Field(
        default=None, 
        description="The sequence of high-level subtask descriptions generated by the planner"
    )
    tool_results: Optional[List[Dict[str, Any]]] = Field(
        default=None, 
        description="Execution outputs from tools invoked during routing"
    )