from pydantic import BaseModel, Field

class Task(BaseModel):
    """Subtask item generated by the Planner agent."""
    task_id: str = Field(..., description="Unique subtask identifier, e.g. task_01")
    intent: str = Field(..., description="Action/category associated with this task, e.g. search, browser, chat")
    description: str = Field(..., description="Detailed instructions of what action needs to be executed")